LosCokis123/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LosCokis123.Data;
using LosCokis123.Models;

namespace LosCokis123.Controllers
{
    public class CommentsController : Controller
    {
        private readonly LosCokis123Context _context;

        public CommentsController(LosCokis123Context context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var losCokis123Context = _context.Comments.Include(c => c.Episode);
            return View(await losCokis123Context.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Episode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string user_id, int episode_id, string coment, int comment_id, [Bind("Id,Coment,EpisodeId,UserId1,CreateAt")] Comment comment)
        {
            var result = await _context.Comments.FirstOrDefaultAsync(c => c.Id == comment_id);
            if (result == default)
            {
                comment.UserId = user_id;
                comment.EpisodeId = episode_id;
                comment.Coment = coment;
                comment.CreateAt = DateTime.Now;
                _context.Add(comment);
            }
            else 
            {
                result.Coment = coment;
                _context.Update(result);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Episodes", new { id = episode_id });
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id", comment.EpisodeId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Coment,EpisodeId,UserId,CreateAt")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id", comment.EpisodeId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Episode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Comments == null)
            {
                return Problem("Entity set 'LosCokis123Context.Comments'  is null.");
            }
            var comment = await _context.Comments.FindAsync(id);
            if (comment != null)
            {
                _context.Comments.Remove(comment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
          return (_context.Comments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LosCokis123/Controllers/FavoritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LosCokis123.Data;
using LosCokis123.Models;

namespace LosCokis123.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly LosCokis123Context _context;

        public FavoritesController(LosCokis123Context context)
        {
            _context = context;
        }

        // GET: Favorites
        public async Task<IActionResult> Index()
        {
            var losCokis123Context = _context.Favorites.Include(f => f.Episode);
            return View(await losCokis123Context.ToListAsync());
        }

        // GET: Favorites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Favorites == null)
            {
                return NotFound();
            }

            var favorite = await _context.Favorites
                .Include(f => f.Episode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favorite == null)
            {
                return NotFound();
            }

            return View(favorite);
        }

        // GET: Favorites/Create
        public IActionResult Create()
        {
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id");
            return View();
        }

        // POST: Favorites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string user_id, int episode_id, int favorite_id, [Bind("Id,Favorite1,EpisodeId,UserId,CreateAt")] Favorite favorite)
        {
            var result = await _context.Favorites.FirstOrDefaultAsync(f => f.Id == favorite_id);
            if (result == default)
            {
                favorite.UserId = user_id;
                favorite.EpisodeId = episode_id;
                favorite.Favorite1 = false;
                favorite.CreateAt = DateTime.Now;
                _context.Add(favorite);
            }
            else 
            {
                result.Favorite1 = !result.Favorite1;
                _context.Update(result);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Episodes", new { id = episode_id });
        }

        // GET: Favorites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Favorites == null)
            {
                return NotFound();
            }

            var favorite = await _context.Favorites.FindAsync(id);
            if (favorite == null)
            {
                return NotFound();
            }
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id", favorite.EpisodeId);
            return View(favorite);
        }

        // POST: Favorites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Favorite1,EpisodeId,UserId,CreateAt")] Favorite favorite)
        {
            if (id != favorite.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favorite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoriteExists(favorite.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id", favorite.EpisodeId);
            return View(favorite);
        }

        // GET: Favorites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Favorites == null)
            {
                return NotFound();
            }

            var favorite = await _context.Favorites
                .Include(f => f.Episode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favorite == null)
            {
                return NotFound();
            }

            return View(favorite);
        }

        // POST: Favorites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Favorites == null)
            {
                return Problem("Entity set 'LosCokis123Context.Favorites'  is null.");
            }
            var favorite = await _context.Favorites.FindAsync(id);
            if (favorite != null)
            {
                _context.Favorites.Remove(favorite);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavoriteExists(int id)
        {
          return (_context.Favorites?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LosCokis123/Controllers/LikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LosCokis123.Data;
using LosCokis123.Models;

namespace LosCokis123.Controllers
{
    public class LikesController : Controller
    {
        private readonly LosCokis123Context _context;

        public LikesController(LosCokis123Context context)
        {
            _context = context;
        }

        // GET: Likes
        public async Task<IActionResult> Index()
        {
            var losCokis123Context = _context.Likes.Include(l => l.Episode);
            return View(await losCokis123Context.ToListAsync());
        }

        // GET: Likes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Likes == null)
            {
                return NotFound();
            }

            var like = await _context.Likes
                .Include(l => l.Episode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (like == null)
            {
                return NotFound();
            }

            return View(like);
        }

        // GET: Likes/Create
        public IActionResult Create()
        {
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id");
            return View();
        }

        // POST: Likes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string user_id, int episode_id, int like_id ,[Bind("Id,Likeop,EpisodeId,UserId,CreateAt")] Like like)
        {
            var result = await _context.Likes.FirstOrDefaultAsync(l => l.Id == like_id);
            if (result == default)
            {
                like.UserId = user_id;
                like.EpisodeId = episode_id;
                like.Likeop = 2;
                like.CreateAt = DateTime.Now;
                _context.Add(like);
            }
            else 
            {
                result.Likeop = result.Likeop == 1? 2 : 1;
                _context.Update(result);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Episodes", new { id = episode_id });
        }

        // GET: Likes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Likes == null)
            {
                return NotFound();
            }

            var like = await _context.Likes.FindAsync(id);
            if (like == null)
            {
                return NotFound();
            }
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id", like.EpisodeId);
            return View(like);
        }

        // POST: Likes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Likeop,EpisodeId,UserId,CreateAt")] Like like)
        {
            if (id != like.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(like);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LikeExists(like.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EpisodeId"] = new SelectList(_context.Episodes, "Id", "Id", like.EpisodeId);
            return View(like);
        }

        // GET: Likes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Likes == null)
            {
                return NotFound();
            }

            var like = await _context.Likes
                .Include(l => l.Episode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (like == null)
            {
                return NotFound();
            }

            return View(like);
        }

        // POST: Likes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Likes == null)
            {
                return Problem("Entity set 'LosCokis123Context.Likes'  is null.");
            }
            var like = await _context.Likes.FindAsync(id);
            if (like != null)
            {
                _context.Likes.Remove(like);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LikeExists(int id)
        {
          return (_context.Likes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LosCokis123/Views/Episodes/Create.cshtml
@model LosCokis123.Models.Episode

@{
    ViewData["Title"] = "Create";
}
<h4>Crear Episodio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Titulo</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <labeL class="control-label">Descripcion</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PodcastId" class="control-label"></label>
                <select asp-for="PodcastId" class ="form-control" asp-items="ViewBag.PodcastId"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Autor</label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Duracion</label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label id="audio" class="control-label">Seleccione su Audio</label>
                <input name="audio" type="file" accept=".mp3" class="form-control-file" required/>
            </div>
            <div class="form-group collapse">
                <label asp-for="AudioUrl" class="control-label"></label>
                <input asp-for="AudioUrl" class="form-control" />
                <span asp-validation-for="AudioUrl" class="text-danger"></span>
            </div>
            <div class="form-group collapse">
                <label asp-for="CreateAt" class="control-label"></label>
                <input asp-for="CreateAt" class="form-control" />
                <span asp-validation-for="CreateAt" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Vuelva a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LosCokis123/Views/Episodes/Delete.cshtml
@model LosCokis123.Models.Episode

@{
    ViewData["Title"] = "Delete";
}

<h3>Esta seguro de eliminar el episodio...</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Titulo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
           Descripcion
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
           Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        @* <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Duration)
        </dd>*@
        <dt class="col-sm-2">
            Audio
        </dt>
        <dd class="col-sm-10">
            @if (Model.AudioUrl.Length > 20)
            {
                @Html.Raw(Model.AudioUrl)
            }
            @if (Model.AudioUrl.Length < 20)
            {
                <br>
                <audio controls loop class="mb-5">
                    <source src="@Html.DisplayFor(model => model.AudioUrl)">
                    Tu navegador no soporta este audio
                </audio>
            }
        </dd>
        @*<dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.CreateAt)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.CreateAt)
        </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Podcast)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Podcast.Title)
        </dd>
        <dt class="col-sm-2">
           Imagen
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Podcast.Image)" width="400" height="200" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar al menu</a>
    </form>
</div>

LosCokis123/Views/Episodes/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using LosCokis123.Areas.Identity.Data

@model LosCokis123.Models.Episode
@inject SignInManager<LosCokis123User> SignInManager
@inject UserManager<LosCokis123User> UserManager

@{
    ViewData["Title"] = "Details";
}
<div>
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">
        <!-- Heading Row-->
        <div class="row gx-4 gx-lg-5 align-items-center my-5 pt-4 pb-4" style="background-color:black; border-radius: 10pt">
            <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="@Html.DisplayFor(model => model.Podcast.Image)" alt="..." /></div>
            <div class="col-lg-5">
                <h1 class="font-weight-light mb-5">@Html.DisplayFor(model => model.Title)</h1>

                <p>Descripcion: @Html.DisplayFor(model => model.Description)</p>
                <p>Autor: @Html.DisplayFor(model => model.Author)</p>
                @if(Model.AudioUrl.Length > 20)
                {
                    @Html.Raw(Model.AudioUrl)
                }
                @if (Model.AudioUrl.Length < 20)
                {
                    <br>
                    <audio controls loop class="mb-5">
                        <source src="@Html.DisplayFor(model => model.AudioUrl)">
                        Tu navegador no soporta este audio
                    </audio>
                }
                
                <table class="table table-sm">
                    <tr>
                        <th>
                            <form asp-controller="Favorites" asp-action="Create" method="post">
                                <input name="episode_id" value="@Model?.Id" hidden />
                                <input name="user_id" value="@UserManager.GetUserId(User)" hidden />
                                <input name="favorite_id" value="@Model?.Favorites.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Id" hidden />

                                @if (Model?.Favorites?.FirstOrDefault(l => l.UserId == UserManager.GetUserId(User))?.Favorite1 != false)
                                {
                                    <button type="submit" value="@(Model?.Favorites?.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Favorite1 != false? Html.Raw("Favorite"):Html.Raw("Unpreferred"))">
                                        <img src="~/images/reaction/favorite.png" width="40" height="40" />
                                    </button>

                                }
                                else
                                {
                                    <button type="submit" value="@(Model?.Favorites?.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Favorite1 != false? Html.Raw("Favorite"):Html.Raw("Unpreferred"))">
                                        <img src="~/images/reaction/unpreferred.png" width="40" height="40" />
                                    </button>
                                }
                            </form>
                        </th>
                        <th>
                            <form asp-controller="Likes" asp-action="Create" method="post" class="mb-5">
                                <input name="episode_id" value="@Model?.Id" hidden />
                                <input name="user_id" value="@UserManager.GetUserId(User)" hidden />
                                <input name="like_id" value="@Model?.Likes.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Id" hidden />
                                @if (Model?.Likes?.FirstOrDefault(l => l.UserId == UserManager.GetUserId(User))?.Likeop != 2)
                                {
                                    <button type="submit" value="@(Model?.Likes?.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Likeop != 2? Html.Raw("Like"):Html.Raw("Dislike"))">
                                        <img src="~/images/reaction/like.png" width="40" height="40" />
                                    </button>
                                }
                                else
                                {
                                    <button type="submit" value="@(Model?.Likes?.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Likeop != 2? Html.Raw("Like"):Html.Raw("Dislike"))">
                                        <img src="~/images/reaction/dislike.png" width="40" height="40" />
                                    </button>
                                }
                            </form>
                        </th>
                        <th>
                            <form asp-controller="Comments" asp-action="Create" method="post">
                                <input name="episode_id" value="@Model?.Id" hidden />
                                <input name="user_id" value="@UserManager.GetUserId(User)" hidden />
                                <input name="comment_id" value="@Model?.Comments.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Id" hidden />
                                <input type="text" name="coment" value="@Model?.Comments.FirstOrDefault(l=>l.UserId == UserManager.GetUserId(User))?.Coment" />
                                <input type="submit" value="@(Model?.Comments?.Any(l=>l.UserId == UserManager.GetUserId(User)) == true? Html.Raw("Update Comment"):Html.Raw("Comment"))" class="btn btn-success" />
                            </form>
                        </th>
                    </tr>
                </table>
            </div>
           
        </div>
    </div>
</div>
<div>
</div>
<div class="container" style="padding: 15px 10px;">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <h2>Titulo del articulo 1</h2>
            <img class="img-fluid rounded mb-4 mb-lg-0" src="~/images/carousel/item1.jpg" alt="..." />
            <figure></figure>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat distinctio illo rerum atque ducimus, laboriosam debitis eum deserunt ab libero quis voluptas, illum, perferendis numquam aut aliquam itaque qui magnam!</p>
            <a href="#" class="btn btn-success">Leer mas</a>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <h2>Titulo del articulo 2</h2>
            <img class="img-fluid rounded mb-4 mb-lg-0" src="~/images/carousel/item2.jpg" alt="..." />
            <figure></figure>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat distinctio illo rerum atque ducimus, laboriosam debitis eum deserunt ab libero quis voluptas, illum, perferendis numquam aut aliquam itaque qui magnam!</p>
            <a href="#" class="btn btn-success">Leer mas</a>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <h2>Titulo del articulo 3</h2>
            <img class="img-fluid rounded mb-4 mb-lg-0" src="~/images/carousel/item3.jpg" alt="..." />
            <figure></figure>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat distinctio illo rerum atque ducimus, laboriosam debitis eum deserunt ab libero quis voluptas, illum, perferendis numquam aut aliquam itaque qui magnam!</p>
            <a href="#" class="btn btn-success">Leer mas</a>
        </div>

    </div>
</div><!-- Fin Sección de Artículos -->
<div>
    @if (User.IsInRole("admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
        <a asp-action = "Index" > Back to List</a>
    }
</div>