LosCokis123/Controllers/EpisodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LosCokis123.Data;
using LosCokis123.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using SpotifyAPI.Web;

namespace LosCokis123.Controllers
{
    public class EpisodesController : Controller
    {
        private readonly LosCokis123Context _context;

        public EpisodesController(LosCokis123Context context)
        {
            _context = context;
        }

        // GET: Episodes
        public async Task<IActionResult> Index()
        {
            var losCokis123Context = _context.Episodes.Include(e => e.Podcast);
            return View(await losCokis123Context.ToListAsync());
        }
        public int NextID()
        {
            int maxId = _context.Episodes.Max(e => e.Id);
            return maxId + 1;
        }

        // GET: Episodes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Episodes == null)
            {
                return NotFound();
            }

            var episode = await _context.Episodes
                .Include(e => e.Podcast)
                .Include(e => e.Likes)
                .Include(e => e.Favorites)
                .Include(e => e.Comments)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (episode == null)
            {
                return NotFound();
            }

            return View(episode);
        }

        // GET: Episodes/Create
        public IActionResult Create()
        {
            ViewData["PodcastId"] = new SelectList(_context.Podcasts, "Id", "Title");
            return View();
        }

        // POST: Episodes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,PodcastId,Author,Duration,AudioUrl,CreateAt")] Episode episode, IFormFile audio)
        {
            int nextID = NextID();
            episode.CreateAt = DateTime.Now;
            string pathdb = "/episode/" + nextID + ".mp3";
            episode.AudioUrl = pathdb;

            if (ModelState.IsValid)
            {
                string path = "wwwroot/episode/" + nextID + ".mp3";
                using (Stream stream = new FileStream(path, FileMode.Create))
                {
                    await audio.CopyToAsync(stream);
                }
                _context.Add(episode);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PodcastId"] = new SelectList(_context.Podcasts, "Id", "Title", episode.PodcastId);
            return View(episode);
        }
        // GET: Episodes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Episodes == null)
            {
                return NotFound();
            }

            var episode = await _context.Episodes.FindAsync(id);
            if (episode == null)
            {
                return NotFound();
            }
            ViewData["PodcastId"] = new SelectList(_context.Podcasts, "Id", "Title", episode.PodcastId);
            return View(episode);
        }

        // POST: Episodes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,PodcastId,Author,Duration,AudioUrl,CreateAt")] Episode episode, IFormFile audio)
        {
            if (id != episode.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string path = "wwwroot/episode/" + id + ".mp3";
                    string pathdb = "/episode/" + id + ".mp3";
                    episode.AudioUrl = pathdb;
                    using (Stream stream = new FileStream(path, FileMode.Create))
                    {
                        await audio.CopyToAsync(stream);
                    }
                    _context.Update(episode);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EpisodeExists(episode.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PodcastId"] = new SelectList(_context.Podcasts, "Id", "Id", episode.PodcastId);
            return View(episode);
        }

        // GET: Episodes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Episodes == null)
            {
                return NotFound();
            }

            var episode = await _context.Episodes
                .Include(e => e.Podcast)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (episode == null)
            {
                return NotFound();
            }

            return View(episode);
        }

        // POST: Episodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Episodes == null)
            {
                return Problem("Entity set 'LosCokis123Context.Episodes'  is null.");
            }
            var episode = _context.Episodes.Include(e => e.Comments)
                .Include(e => e.Likes)
                .Include(e => e.Favorites)

            .FirstOrDefault(e => e.Id == id);
            if (episode != null)
            {
                _context.Episodes.Remove(episode);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EpisodeExists(int id)
        {
          return (_context.Episodes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LosCokis123/Controllers/PodcastsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LosCokis123.Data;
using LosCokis123.Models;
using System.Web;
using System.IO;
using SpotifyAPI.Web;

namespace LosCokis123.Controllers
{
    public class PodcastsController : Controller
    {
        private readonly LosCokis123Context _context;

        public PodcastsController(LosCokis123Context context)
        {
            _context = context;
        }

        // GET: Podcasts
        public async Task<IActionResult> Index()
        {
              return _context.Podcasts != null ? 
                          View(await _context.Podcasts.ToListAsync()) :
                          Problem("Entity set 'LosCokis123Context.Podcasts'  is null.");
        }
        public int NextID()
        {
            int maxId = _context.Podcasts.Max(e => e.Id);
            return maxId + 1;
        }

        // GET: Podcasts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Podcasts == null)
            {
                return NotFound();
            }

            var podcast = await _context.Podcasts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (podcast == null)
            {
                return NotFound();
            }

           return View(podcast);
        }

        // GET: Podcasts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Podcasts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Author,Image,CreateAt")] Podcast podcast, IFormFile image)
        {
            int nextID = NextID();
            podcast.CreateAt = DateTime.Now;
            string pathdb = "/podcast/" + nextID + ".jpg";
            podcast.Image = pathdb;

            if (ModelState.IsValid)
            {
                string path = "wwwroot/podcast/" + nextID + ".jpg";
                using (Stream stream = new FileStream(path, FileMode.Create))
                {
                    await image.CopyToAsync(stream);
                }
                _context.Add(podcast);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(podcast);
        }

        // GET: Podcasts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Podcasts == null)
            {
                return NotFound();
            }

            var podcast = await _context.Podcasts.FindAsync(id);
            if (podcast == null)
            {
                return NotFound();
            }
            return View(podcast);
        }

        // POST: Podcasts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Author,Image,CreateAt")] Podcast podcast, IFormFile image)
        {
            if (id != podcast.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string path = "wwwroot/podcast/" + id + ".jpg";
                    string pathdb = "/podcast/" + id + ".jpg";
                    podcast.Image = pathdb;
                    using (Stream stream = new FileStream(path, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                    _context.Update(podcast);
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PodcastExists(podcast.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(podcast);
        }

        // GET: Podcasts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Podcasts == null)
            {
                return NotFound();
            }

            var podcast = await _context.Podcasts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (podcast == null)
            {
                return NotFound();
            }

            return View(podcast);
        }

        // POST: Podcasts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Podcasts == null)
            {
                return Problem("Entity set 'LosCokis123Context.Podcasts'  is null.");
            }
            var podcast = _context.Podcasts.Include(p => p.Episodes)
                .ThenInclude(e => e.Comments)
                .Include(p => p.Episodes)
                .ThenInclude(e => e.Likes)
                .Include(p => p.Episodes)
                .ThenInclude(e => e.Favorites)
                .FirstOrDefault(p => p.Id == id);

            if (podcast != null)
            {
                _context.Podcasts.Remove(podcast);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PodcastExists(int id)
        {
          return (_context.Podcasts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LosCokis123/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LosCokis123</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LosCokis123.styles.css" asp-append-version="true" />
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>@ViewData["Title"] - LosCokis123</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/styles.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="~/images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" media="all" href="~/css/player.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">@*
    *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <header>
        <div class="container-fluid">

            <div class="row justify-content-center">
                <div class="col-xl-9 d-flex align-items-center justify-content-lg-between">
                    <h1 class="logo me-auto me-lg-0"><a href="index.html">Ciencia de Datos</a></h1>
                    <!-- Uncomment below if you prefer to use an image logo -->
                    <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

                    <nav id="navbar" class="navbar order-last order-lg-0">
                        <ul>
                            <li><a asp-controller="Home" asp-action="Index" class="nav-link scrollto">Pagina Principal</a></li>
                            @if (User.IsInRole("admin"))
                            {
                                <li><a asp-controller="Podcasts" asp-action="Index" class="nav-link scrollto">Podcast</a></li>
                            }
                            <li><a asp-controller="Episodes" asp-action="Index" class="nav-link scrollto">Explorar</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Ciencia de Datos</span> <i class="bi bi-chevron-down"></i></a>
                                <ul>
                                    <li><a href="#">Sobre la carrera</a></li>
                                    <li><a href="#">Imagenes</a></li>
                                    <li><a href="#">Informacion</a></li>
                                </ul>
                            </li>
                        </ul>
                        <i class="bi bi-list mobile-nav-toggle"></i>
                    </nav><!-- .navbar -->
                    <partial name="_LoginPartial" />
                </div>
            </div>

        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="text-center text-lg-start bg-white text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
                <span>Contactanos mediante nuestras redes sociales:</span>
            </div>
            <!-- Left -->
            <!-- Right -->
            <div>
                <a href="" class="me-4 link-secondary">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="" class="me-4 link-secondary">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="" class="me-4 link-secondary">
                    <i class="fab fa-google"></i>
                </a>
                <a href="" class="me-4 link-secondary">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="" class="me-4 link-secondary">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="" class="me-4 link-secondary">
                    <i class="fab fa-github"></i>
                </a>
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->
        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3 text-secondary"></i>Univalle
                        </h6>
                        <p>
                            La universidad del valle presenta su nueva carrera enfocada a ciencia de datos
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Informacion
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Malla Curricular</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Sobre la carrera</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Bibliografias</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Materias</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Contamos con:
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Laboratorios</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Biblioteca</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Campos recreativos</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Areas verdes</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">Contactos</h6>
                        <p><i class="fas fa-home me-3 text-secondary"></i>Bolivia-Univalle</p>
                        <p>
                            <i class="fas fa-envelope me-3 text-secondary"></i>
                            univalle.edu
                        </p>
                        <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
                        <p><i class="fas fa-print me-3 text-secondary"></i> + 01 234 567 89</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
            © 2023 Copyright:
            <a class="text-reset fw-bold" href="https://univalle.edu/">UNIVERSIDAD DEL VALLE</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!--footer section end -->
    <!-- Javascript files-->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-3.0.0.min.js"></script>
    <script src="~/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/custom.js"></script>
    <!-- javascript -->
    <script src="~/js/owl.carousel.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });
    </script>
</body>
</html>